main: org.kalbinvv.purgomalumspigot.PurgoMalumSpigot
name: PurgoMalumSpigot
version: '1.0'
api-version: 1.19
description: Simple anti swear system, that use PurgoMalum API.
softdepend: [bStats]
commands:
    purgomalum:
        description: Main plugin command.
        usage: /purgomalum reload
        permission: purgomalum.reload
